### ISSUE TITLE
EPIC 1 Repository and Deploy Early

### ISSUE THREAD

**Issue by Harmonica-Men** [Harmonica-Men/AstroShop#18]
**Description:** Set up Django Project into GitPod Workspaces

**Details:**
- [x] [USER STORY:](https://github.com/users/Harmonica-Men/projects/10/views/1?pane=issue&itemId=70364129) Set up Locally the VS Code IDE
- [x] [USER STORY:](https://github.com/users/Harmonica-Men/projects/10/views/1?pane=issue&itemId=70098555) Set up GitHub repository
- [x] [USER STORY:](https://github.com/users/Harmonica-Men/projects/10?pane=issue&itemId=70105394) Create a working Django app
- [x] [USER STORY:](https://github.com/users/Harmonica-Men/projects/10/views/1?pane=issue&itemId=70105449) Deploy to Heroku
- [x] [USER STORY:](https://github.com/users/Harmonica-Men/projects/10/views/1?pane=issue&itemId=70109025) Set up the IDE workspace on GitPod
