### ISSUE TITLE
EPIC 2 (Basic Shop Functionality)

### ISSUE THREAD

**Issue by Harmonica-Men** [Harmonica-Men/AstroShop#19]
**Description:** Implement basic shop functionality including models, views, and templates.
**Details:**
  - [x] [USER-STORY:](https://github.com/users/Harmonica-Men/projects/10/views/1?pane=issue&itemId=70132743) Define the models for blog posts (Post, Category, Comment, User).
  - [x] [USER-STORY:](https://github.com/users/Harmonica-Men/projects/10/views/1?pane=issue&itemId=70135804) Create views to list all posts, view individual posts, and manage categories /... etc
  - [x] [USER-STORY:](https://github.com/users/Harmonica-Men/projects/10/views/1?pane=issue&itemId=70138078) Design templates for the blog homepage, individual post pages, comment, ... etc pages
  - [x] [USER-STORY:](https://github.com/users/Harmonica-Men/projects/10/views/1?pane=issue&itemId=70139779) Implement URL routing for the blog.
